# This is a TOML config file.

##### RPC configrations #####

# RPC endpoint for ethereum chain
eth_RPC_URL = "http://localhost:8545"

##### DB configrations #####
mongo_DB_url = "mongodb://localhost:27017"

##### Server configrations #####
server_port = "8080"
polling_interval = "5s"


confirmation_blocks = "5"

##### Contract Addresses #####
rollup_address = "0x0000000000000000000000000000000000000000"
